# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provision "docker" do |d|
    d.build_image "/vagrant",
    args: "-t calculator"
  end
  config.vm.hostname = "calculatorGolang"
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "private_network", ip: "55.55.55.5"

  config.vm.provision "file", source: "calculator.go", destination: "$HOME/calculator.go"
  config.vm.provision "file", source: "Dockerfile", destination: "$HOME/Dockerfile"
  config.vm.provision "file", source: "script_run_microservice.sh", destination: "$HOME/script_run_microservice.sh"
end